import type { RiskProfile } from "@crucible-trader/sdk";

import type { TradeFill } from "./types.js";

export interface ReportPayload {
  readonly runName: string;
  readonly summary: Record<string, number>;
  readonly trades: ReadonlyArray<TradeFill>;
  readonly riskProfile: RiskProfile;
}

const toPercent = (value: number): string => {
  return `${(value * 100).toFixed(2)}%`;
};

export const buildReportMarkdown = (payload: ReportPayload): string => {
  const lines: string[] = [];
  lines.push(`# run ${payload.runName}`);
  lines.push("");
  lines.push("## summary");
  lines.push("");
  lines.push("| metric | value |");
  lines.push("| --- | --- |");
  for (const [metric, value] of Object.entries(payload.summary)) {
    lines.push(`| ${metric} | ${value.toFixed(4)} |`);
  }

  lines.push("");
  lines.push("## trades");
  lines.push("");
  lines.push(`- fills: ${payload.trades.length}`);
  const realized = payload.trades.reduce((acc, trade) => acc + trade.pnl - trade.fees, 0);
  lines.push(`- realized pnl: ${realized.toFixed(2)}`);

  lines.push("");
  lines.push("## risk profile");
  lines.push("");
  lines.push(
    `- max position: ${toPercent(payload.riskProfile.maxPositionPct)} | kill switch: ${toPercent(payload.riskProfile.globalDDKillPct)}`,
  );
  lines.push(
    `- daily loss limit: ${toPercent(payload.riskProfile.maxDailyLossPct)} | per order cap: ${toPercent(payload.riskProfile.perOrderCapPct)}`,
  );
  lines.push(`- cooldown: ${payload.riskProfile.cooldownMinutes} minutes`);
  lines.push("");
  lines.push("_generated by crucible trader phase 0 engine_");

  return `${lines.join("\n")}\n`;
};
